src/main/java/com/even/zaro/service/ProfileService.java

-  메인 브랜치에 반영된 ProfileService의 UserException 버그 수정
---
```
// 기존 버그난 코드
User user = userRepository.findById(request.getUserId())
.orElseThrow(UserException::NotFoundUserException);
// 수정된 코드 
User user = userRepository.findById(request.getUserId())
.orElseThrow(() -> new UserException(ErrorCode.EXAMPLE_USER_NOT_FOUND));
```
---
---
---
---
- 부득이하게 빠르게 머지 하겠습니다
---

Refactor : 예외 던지는 방식 변경

---

src/main/java/com/even/zaro/controller/ProfileController.java
src/main/java/com/even/zaro/service/ProfileService.java

conflix 해결 시 import 잘못 설정된 부분 수정, 불필요 import 삭제
---
- profile 컨트롤러, 서비스의 import 단
---
---
- main에 있는 상태고 급한 수정이라 바로 머지하겠습니다
---

profile/fix : conflix 해결 시 import 잘못 설정된 부분 수정, 불필요 import 삭제

---

src/main/resources/application.yaml

환경변수 email.verification.url를 읽지 못하는 문제 해결
---
- application.yaml 이전코드
```
email:
verification-url: ${EMAIL_VERIFICATION_URL}
```
- application.yaml 수정 후 코드
```
email:
verification:
url: ${EMAIL_VERIFICATION_URL}
```
---
- 수정 전 에러메시지
```
org.springframework.util.PlaceholderResolutionException: 
Could not resolve placeholder 'email.verification.url' in value "${email.verification.url}"
```
- 수정 후 resolved !!
---
---
- @Saaad9 : 동훈님이 찾으신 이유
나현님 사용 방식은 yaml의 flat 구조, 유림 동훈은 nested 구조라, 서로 적용이 안되는? 그보다.. 구조가 다르대요
---

Bug : 환경변수 email.verification.url를 읽지 못하는 문제 해결

---

src/main/java/com/even/zaro/dto/profile/UserPostDto.java

- post 기능들 머지 내용 중, profile service에는 imageUrl -> thumbnailUrl로 컬럼 및 변수명칭이 변경되어있으나, 해당 DTO에는 변경되지 않아 뜨는 오류 수정
---
- UserPostDto 수정
---
---
- 메인 머지된 상태이므로 quick fix

Bug : DTO에는 imageUrl -> thumbnailUrl로 명칭 변경되지 않은 에러 수정

---

src/main/java/com/even/zaro/service/EmailService.java

- 비밀번호 재설정 메일 프론트 개발 주소 추가
---
- 비밀번호 재설정 메일 프론트 개발 주소 추가
---
---
---
---
- 프론트 요청사항입니다. 기능 수정 없습니다. 추후 삭제 될 부분입니다.
---

hotfix: 비밀번호 재설정 메일 프론트 개발 주소 추가

---

src/main/java/com/even/zaro/dto/favorite/FavoriteAddRequest.java
src/main/java/com/even/zaro/dto/favorite/FavoriteEditRequest.java
src/main/java/com/even/zaro/global/exception/favorite/FavoriteException.java
src/test/java/com/even/zaro/favorite/FavoriteApiTest.java

- Favorite API 예외 테스트 케이스 추가 및 테스트 완료
---
- #38 참고 부탁드립니다!
---
> ![image](https://github.com/user-attachments/assets/ec162dff-4ca7-4a28-8a61-59b4900af5f2)
- 모든 성공, 예외 테스트 통과
---
---
---
- 
---
- close #38

Test/favorite exception Favorite API 예외 테스트 케이스 추가

---

src/main/java/com/even/zaro/service/EmailService.java
src/main/resources/email/email-verification-template.html
src/main/resources/email/password-reset-template.html

- 이메일 인증/비밀번호 재설정 메일 템플릿 적용
---
- 이메일 인증/비밀번호 재설정 메일 템플릿 적용
- 기능 변경은 없고, 스타일링만 변경되었습니다. 
- 잘 동작하는 것 확인했고, 토큰도 유효합니다. -> 클릭시 각 로그인, 비밀번호 재설정 배포 페이지로 리다이랙트
- 비밀번호 재설정 부분에는 혹시 몰라서 개발 url도 넣어놨는데 html 마지막 줄에서 제거하면 될 것 같습니다. 
---
---
---
---
- 급한 일 아니지만.. 집중이 안되서 한번 해봤습니다.
- https://my.stripo.email/login -> 여기에서 슥슥 해서 html 적용했는데 생각보다 괜찮아보이는데 어떠신가요~? ㅎㅎㅎ
아래와 같이 할 수 있음.
---

Fix/email detail 이메일 인증/비밀번호 재설정 메일 템플릿 적용

---

src/main/java/com/even/zaro/config/QueryDslConfig.java

- 너무 죄송합니다....ㅠㅠㅠㅠㅠㅠㅠㅠ 담부터 제대로 확인할게요..

QueryDslConfig 파일 복구

---

src/main/java/com/even/zaro/controller/FavoriteController.java
src/main/java/com/even/zaro/controller/GroupController.java
src/main/java/com/even/zaro/dto/favorite/FavoriteAddRequest.java
src/main/java/com/even/zaro/global/ErrorCode.java
src/main/java/com/even/zaro/repository/PlaceRepository.java
src/main/java/com/even/zaro/service/FavoriteService.java
src/test/java/com/even/zaro/favorite/FavoriteApiTest.java
src/test/java/com/even/zaro/group/GroupAPITest.java
src/test/java/com/even/zaro/map/MapApiTest.java

- 서비스 코드의 필드 또는 로직이 달라짐에 따라 미처 변경하지 못했던 테스트코드에서 오류 발생한 것을 수정했습니다.
---
- 테스트 코드의 메서드 변경 
- 주석 제거
- 각 테스트의 메서드별로 테스트 진행 시 모두 성공
---
---
---
---
- GroupApiTest 제외하고는 클래스 단위로 테스트 진행 시 초기화가 되지 않은 채로 같이 테스트가 진행돼서 그런지 몇개 오류가 발생합니다
하지만 해당 테스트 코드의 목적 자체가 개별 기능의 성공, 예외 테스트이기 때문에. . 추후 각 테스트가 진행되고 clean? 작업같은 것을 추가하거나 
@BeforeEach 같은 것을 추가해서 한꺼번에 실행도 성공하도록 수정하겠습니다.
---
- close #75

Test/fix-error 지도, 그룹, 즐겨찾기 API 테스트 코드 오류 수정

---

src/main/java/com/even/zaro/controller/PostController.java
src/main/java/com/even/zaro/dto/post/ReportRequestDTO.java
src/main/java/com/even/zaro/dto/post/ReportResponseDto.java
src/main/java/com/even/zaro/entity/Post.java
src/main/java/com/even/zaro/entity/PostReport.java
src/main/java/com/even/zaro/entity/ReportReasonType.java
src/main/java/com/even/zaro/global/ErrorCode.java
src/main/java/com/even/zaro/repository/PostReportRepository.java
src/main/java/com/even/zaro/repository/PostRepository.java
src/main/java/com/even/zaro/service/PostReportService.java
src/main/java/com/even/zaro/service/PostService.java

- 게시글 신고 API 구현
---
- 신고 관련 공통 DTO, ENUM 생성
- `ReportReasonType`
- `ReportRequestDTO`
- 게시글 신고 기능 구현
- 동일 게시물 중복 신고 차단
- 신고 횟수 누적시(5회) 숨김처리
-  신고된 게시글 리스트, 상세 조회 불가
- 홈 미리보기에서도 숨김처리되어서 해당 게시글 조회 불가
---
>
| 비로그인 사용자 | 이메일 미인증 사용자 | 본인 게시글 신고 |
|---------|---------|---------|
|![비로그인 사용자](https://github.com/user-attachments/assets/9cd9af17-eecc-4a79-8ee5-b331e330a508)|![이메일 미인증 유저](https://github.com/user-attachments/assets/2cac6bd9-4b00-4270-b2b8-85250611a678)|![본인게시글 신고](https://github.com/user-attachments/assets/a7127f43-5b2e-488a-9f4a-f202c6407edb)|
| 존재하지 않는 게시글 신고 | 이미 신고된 게시글 | ETC - 사유 안적었을때 |
|---------|---------|---------|
|![존재하지 않는 게시글 신고](https://github.com/user-attachments/assets/ac70bf67-89c3-4ec6-9fa6-208e1dc01304)|![test1 - …

Feat/postReport : 게시글 신고 API 구현

---

build.gradle
src/main/java/com/even/zaro/dto/post/ReportRequestDTO.java
src/main/java/com/even/zaro/entity/Post.java
src/main/java/com/even/zaro/global/ErrorCode.java
src/main/java/com/even/zaro/mapper/PostMapper.java
src/main/java/com/even/zaro/service/CommentReportService.java
src/main/java/com/even/zaro/service/PostLikeService.java
src/main/java/com/even/zaro/service/PostReportService.java
src/main/java/com/even/zaro/service/PostService.java

- Mapstruct 기반 PostMapper 적용 리팩토링 진행
- findPostOrThrow 공통 메서드 분리 및 적용
---
> 포스트맨 이상 없음 확인
| 작성 | 수정 | 삭제 |
|---------|---------|---------|
|![게시글 작성](https://github.com/user-attachments/assets/7ea29e3a-9eb3-4b7d-9518-d291278c1866)|![게시글 수정](https://github.com/user-attachments/assets/039ed371-e761-4319-bfdb-e9858bdf383c)|![게시글 삭제](https://github.com/user-attachments/assets/2c17e8d5-836c-4f28-bec6-5e61944eab28)|
| 리스트조회 | 상세조회 |
|---------|---------|
|![리스트 조회](https://github.com/user-attachments/assets/dd3caa41-33f1-4c7d-8d71-7b40d79e05a7)|![게시글 상세조회](https://github.com/user-attachments/assets/5efe55b0-2c28-4ae8-8abe-c9bd33b245da)|
---
---
- 동훈님이 먼저 머지해주셔서 build.gradle은 삭제하고 push 했습니다!
- #122 
- #121

Ref/post : 멘토링 피드백 적용

---

src/main/java/com/even/zaro/dto/auth/KakaoUserInfoDto.java
src/main/java/com/even/zaro/entity/Gender.java

- 카카오 로그인 버그 수정
---
- 카카오 로그인 버그 수정
- NPE 해결을 위해 switch 문 앞에 null 체크
---
---
---
---
- Gender enum 변경 후 switch문 사용, null 체크 빼먹음
---

Fix/oauth 카카오 로그인 버그 수정

---

Jenkinsfile

- 젠킨스 파이프라인 수정
---
- 무중단 배포(B서버) 문제 해결 및 동시 빌드 오류 해결
- 이미 B 프록시일 때 토글 되어 A 프록시로 설정되지 않도록 boolean 확인 후 스테이지 실행
- 빌드 중 다음 빌드 실행되지 않고 순차 실행 옵션 설정
- env 파일 B 서버에서 관리로 A 서버에서 전송 코드 삭제 (B서버 env 적용 완료)
- 서버 용량 문제 해결을 위해 중복 이미지 등 안쓰는 이미지, 컨테이너, 네트워크 삭제 (`docker system prune -f`)
---
젠킨스 내부 스크립트 확인 완료
B 서버 프록시 시 API 확인 완료
---
---
---
- 제발..
---
- 관련 이슈 번호: Fixes #139  Fixes #140

Fix/jenkinsfile 젠킨스 파이프라인 수정

---

src/main/java/com/even/zaro/repository/PostRepository.java
src/main/java/com/even/zaro/service/PostService.java

- 인기게시글 기간 제한 추가
---
> 
| 1일 제한 조회 [ 최근작성x = 빈 배열 ] | 7일 제한 조회 | MySql |
|-------|-------|-------|
|![스크린샷 2025-06-09 오전 2 05 43](https://github.com/user-attachments/assets/f26ba240-10fe-4356-a269-2a7ba89b8fb8)|![스크린샷 2025-06-09 오전 2 10 05](https://github.com/user-attachments/assets/1ea7f032-6f8e-4518-9139-90bf5cbf28c8)|![스크린샷 2025-06-09 오전 2 11 28](https://github.com/user-attachments/assets/b9872d55-86be-448b-b4b5-81e790ec996b)|
| 날짜 임시 설정 | 수정 적용된 리스트 | 1일 제한 재 조회 |
|-------|-------|-------|
|![스크린샷 2025-06-09 오전 2 13 06](https://github.com/user-attachments/assets/5daac03e-0365-4fe5-87cf-7b7fe77eb8ab)|![스크린샷 2025-06-09 오전 2 13 12](https://github.com/user-attachments/assets/0ff8009c-f675-4f94-a1f8-e3cf7ccdc93b)|![스크린샷 2025-06-09 오전 2 …

feat: 실시간 인기 게시글 기간 제한 추가

---

src/main/java/com/even/zaro/mapper/PostMapper.java
src/main/java/com/even/zaro/repository/PostRepository.java
src/main/java/com/even/zaro/service/PostService.java

- 게시글 리스트조회 Mapper 수정, 인기게시글 score 관련 수정
---
- 리스트 content 조회시 `<br>, \n , \ `등 제거 후 보여지도록 적용
- 주간 인기게시글 score 0점 적용되어 나타나는 버그 수정 (score > 0 조건 조회 )
---
| 1~5 기본 순위 | 리스트 조회 시 | 쿼리로 score 임시 변경 | 리스트 조회 시 |
|-------|-------|-------|-------|
|![스크린샷 2025-06-09 오후 3 12 40](https://github.com/user-attachments/assets/f16eb281-d182-4ba1-bc8a-b1a9a5f2135e)|![스크린샷 2025-06-09 오후 3 13 47](https://github.com/user-attachments/assets/bf44a31d-0eb5-4af9-95bb-a00c123c3ac3)|![스크린샷 2025-06-09 오후 3 14 28](https://github.com/user-attachments/assets/84c8c4dd-d494-4539-a37b-a4bda1ffe84e)|![스크린샷 2025-06-09 오후 3 14 44](https://github.com/user-attachments/assets/7108cffe-6f6a-4a23-bc62-e4cb44bce5eb)|
| 게시글 수정 | 리스트 조회 시 |
|-------|-------|
|![스크린샷 2025-06-09 오후 5 10 …

Fix/post 게시글 관련 버그 수정

---

src/main/java/com/even/zaro/controller/MapController.java
src/main/java/com/even/zaro/service/MapService.java

- 모든 장소 조회 api 구현
---
- api 추가
---
> ![image](https://github.com/user-attachments/assets/386505bb-812a-4118-8011-d7ad9eff3b85)
> ![image](https://github.com/user-attachments/assets/081b1b60-9b1d-4fac-b5c9-8b0100934b7f)
- 등록되어있는 모든 장소를 반환합니다.
---
- [] 반복 코드 메서드로 분리
---
---
- 프론트엔드에서 초기 지도 페이지 로딩 시 등록되어있는 모든 마커를 불러오려면 이 기능이 필요했습니다.
---
- close #154

feat : 모든 장소 조회 api 

---

src/main/java/com/even/zaro/repository/PostRepository.java
src/main/java/com/even/zaro/service/PostService.java

- findPostOrThrow 공통 메서드 수정
---
- 나현님이 말씀주셨던 부분입니다! 잠시 볼일이있어 다녀온다고 늦었습니다 죄송합니다🥲

ref: 공통 로직 수정

---

src/main/java/com/even/zaro/service/MapService.java

- 인근 장소 조회 시 내림차순 조회
---
> <img width="404" alt="image" src="https://github.com/user-attachments/assets/a2a66723-7376-4bd1-8b9b-014841e80b98" />
- 위 이미지처럼 내림차순 조회하도록 변경 ( 프론트에서 내림차순 정렬로 받아야합니다.)
---
> <img width="376" alt="image" src="https://github.com/user-attachments/assets/d1266b06-5137-4b31-b10e-ee447c1d9b9c" />
- 내림차순 정렬 테스트 완료
---
---
---
- 오름차순, 내림차순으로 인자를 받아서 구현할 수도 있었지만,, 일단 화면에 보이는 기능 구현에 우선을 두고 추가했습니다.
---

feat : 인근 장소 조회 시 내림차순 정렬

---

build.gradle
src/main/java/com/even/zaro/global/jwt/JwtAuthFilter.java
src/main/java/com/even/zaro/global/scheduler/UserScheduler.java
src/main/resources/application.yaml

- 로그 추가 및 정리
---
- 캐시 라이브러리 추가 (Caffeine)
- 스케줄러 로그 추가
- jpa, hibernate sql 쿼리 중복 로그 중 hibernate만 남김
- 스웨거 ui 필터 거치지 않도록 path 추가 (가끔 만료 토큰 문제로 에러 나는 부분 해결)
- 만료 토큰, 로그아웃 후 토큰(exception trace 따로 삭제하지 않음) log warn 처리
---
|만료 토큰 | 로그아웃후 블랙리스트 토큰 |
|--------|-----------|
|![image](https://github.com/user-attachments/assets/6000f864-96c5-4533-9bbf-2b5217bfa440)|![image](https://github.com/user-attachments/assets/9ca043be-7a98-4853-9f9c-2fb88783af05)|
|쿼리 출력 설정 수정 전| 수정 후 |
|--------|-----------|
|![image](https://github.com/user-attachments/assets/5d5ad8cb-88d5-46f3-b217-c55e4e921e23)|![image](https://github.com/user-attachments/assets/47a0be4f-e8ea-430e-b093-73367b88ffec)|
---
---
---
- 하려던 작업은 아닌데.. 눈에 보여서 처리 했습니다 ㅎㅎ
---

Fix/ex log 로그 추가 및 정리

---

src/main/java/com/even/zaro/dto/map/PlaceResponse.java
src/main/java/com/even/zaro/service/MapService.java

-  kakoPlaceId 응답 객체 추가
---
-  kakoPlaceId 응답 객체 추가
---
> <img width="404" alt="image" src="https://github.com/user-attachments/assets/1f0a987d-e6f2-4b66-8676-b246e839bb6a" />
- kakaoPlaceId 응답객체에 추가했습니다.
---
---
---
- 프론트에서 DB 조회 기반 즐겨찾기 추가를 할 때, kakaoPlaceId가 없어서 작업할 수 없어서 추가하게 되었습니다
- 빠른 Approve 해주시면 너무 감사합니다.
---

fix : kakoPlaceId 응답 객체 추가

---

src/main/java/com/even/zaro/dto/post/PostCreateRequest.java
src/main/java/com/even/zaro/dto/post/PostUpdateRequest.java
src/main/java/com/even/zaro/service/ProfileService.java
src/test/java/com/even/zaro/unit/service/PostReportTest.java
src/test/java/com/even/zaro/unit/service/PostServiceTest.java

- 테스트 코드 작성
- 프로필부분 stripHtmlTags 추가
---
- 게시글 관련 테스트코드 추가
- 프로필에 br태그 및 // 등 특정 문자 제거코드 추가
---
> 
| PostServiceTest | PostReportTest |
|-------|-------|
|<img width="813" alt="스크린샷 2025-06-18 오전 10 24 19" src="https://github.com/user-attachments/assets/50773e9b-350a-4b85-97aa-d137b9125ccc" />|<img width="708" alt="스크린샷 2025-06-18 오전 10 25 00" src="https://github.com/user-attachments/assets/e616c691-2652-4d39-8d90-504780843496" />|
| 게시글 수정 | profile 작성 게시글 조회시 |
|-------|-------|
|<img width="830" alt="스크린샷 2025-06-18 오전 10 19 06" src="https://github.com/user-attachments/assets/72f2e3e8-e7d8-44ef-a98a-c19dc628915f" />|<img width="830" alt="스크린샷 2025-06-18 오전 10 19 24" src="https://github.com/user-attachments/assets/fabdf6ce-8b23-4621-93a8-708a5bf40146" …

Feat/post test 게시글 관련 테스트 코드 작성 및 특정 문자 제거 추가

---

src/main/java/com/even/zaro/controller/GroupController.java
src/main/java/com/even/zaro/service/GroupService.java

-그룹 추가시 응답 객체에 그룹 정보 추가
---
- 서비스 로직 수정 (응답객체 추가)
---
> ![image](https://github.com/user-attachments/assets/cc6b154b-63d5-4e33-acbe-5652e20969e6)
---
---
-ex: ID 중복 시 예외 처리 발생
---
- groupName과 groupId 내려달라고 하셨는데, 기존 dto 객체 재활용하여 몇가지 정보를 더 포함해서 응답합니다
---

ref : 그룹 추가시 응답 객체에 그룹 정보 추가 (프론트 요청사항)

---

src/main/java/com/even/zaro/dto/post/PostRankResponseDto.java

- 인기게시글dto에 카테고리 추가
---
- 델스때 말씀주셨던 undefined 수정을 위해 카테고리를 추가하게 되었습니다.

feat: DTO에 카테고리 추가

---

src/main/java/com/even/zaro/config/security/SecurityConfig.java
src/main/java/com/even/zaro/controller/MapController.java
src/main/java/com/even/zaro/global/jwt/JwtUtil.java

- 인근 장소 조회 API 인증 헤더 제거하였습니다. 프론트 측에서 액세스 토큰을 보내지 않게 되어 후속 조치입니다.
- 나현님 요청사항: jwt 시간 만료 15 -> 30
---
- 인증 헤더 제거
- 나현님 요청사항: jwt 시간 만료 15 -> 30
---
- 
---
---
- SwaggerUI
---
- 빠른 Approve 부탁드립니다
---

ref : 인근 장소 조회 API 인증 헤더 제거

---

src/main/java/com/even/zaro/dto/post/PostDetailResponse.java
src/main/java/com/even/zaro/mapper/PostMapper.java
src/main/java/com/even/zaro/service/ProfileService.java

- 게시글 상세조회에도 stripHtmlTags 적용되었던게 default String stripHtmlTags(String html) { 로 해서 전체 적용이 된거라고 하더라구요..! @ Named 를 써서 게시글 리스트조회시에만 적용되도록 했습니다.
연결이 상당히 끊기는데.. 얼른 내려서 빨리 작업 하겠습니다..ㅠㅠㅠ 죄송합니다

ref: @Named 사용으로 리스트조회에만 적용

---

docker-compose.ngrinder.local.yml

- ngrinder local 파일 추가
---
- `docker-compose.ngrinder.local.yml` 파일 추가
---
> 명령어 실행 후 localhost:8081 접속
---
---
---
- 실행 방법은 #189 을 꼭 참고해주세요!!!
- 배포 환경 영향 없습니다, 각자 로컬 테스트용 ~
---

setting/ngrinder : ngrinder local 파일 추가

---

src/main/java/com/even/zaro/global/scheduler/UserScheduler.java
src/main/java/com/even/zaro/repository/UserRepository.java

- enum converter 사용으로 코드 변경
---
- 테스트 에러 해결을 위함입니다.
- enum converter 사용으로 코드 변경
- 테스트 환경에서 h2를 사용하는데 DATE(u.last_login_at)으로는 인식을 못해서 CAST(u.last_login_at AS DATE)로 변경했습니다.
---
---
---
---
---

fix: enum converter 사용으로 코드 변경
