code-is-evenly-cooked/even-zaro-back

- src/main/java/com/even/zaro/controller/ApiTestController.java
- src/main/java/com/even/zaro/global/ApiResponse.java
- src/main/java/com/even/zaro/global/ErrorCode.java
- src/main/java/com/even/zaro/global/exception/GlobalExceptionHandler.java
- src/main/java/com/even/zaro/healthcheck/HealthCheckController.java
- API 응답객체 변경
---
- 변경된 파일 및 폴더 구조
- 구현한 주요 기능 및 변경점
- GlobalException.java : 실패 코드 기본값 설정
- ApiResponse.java : 응답의 성공, 실패 형태 변경
- HealthCheck, ApiTest 컨트롤러 예시 응답 변경
피드백 사항
- ApiResponse 인자 순서 변경
- ErrorCode 파일로 오류 코드 관리 
- GlobalException 대거 수정 (응답형식 통일)
---
> ![image](https://github.com/user-attachments/assets/cfde45d2-20a2-410a-82b1-6fe70206fd03)
- 성공 시 
> ![image](https://github.com/user-attachments/assets/641538ce-fadc-4d0b-9582-4002eb17d00e)
- 잘못된 url 요청 
> ![image](https://github.com/user-attachments/assets/6b12f4c2-eb27-42f5-913d-ae4f5401ec53)
- 사용자 예외 예시
> ![image](https://github.com/user-attachments/assets/080953a3-5f74-4b04-b391-f0d7d1bdfb41)
- 예시 예외 
---
---
- ApiTestController 
- HealthCheckController
---
---
> Config/api-response API 응답 객체 변경 

- src/main/java/com/even/zaro/controller/FavoriteController.java
- src/main/java/com/even/zaro/controller/GroupController.java
- src/main/java/com/even/zaro/controller/ProfileController.java
- src/main/java/com/even/zaro/dto/favorite/FavoriteAddRequest.java
- src/main/java/com/even/zaro/dto/profile/GroupCreateRequest.java
- src/main/java/com/even/zaro/global/ErrorCode.java
- src/main/java/com/even/zaro/global/exception/favorite/FavoriteException.java
- src/main/java/com/even/zaro/global/exception/group/GroupException.java
- src/main/java/com/even/zaro/service/FavoriteService.java
- src/main/java/com/even/zaro/service/GroupService.java
- src/main/java/com/even/zaro/service/ProfileService.java
- src/main/resources/application.yaml
- Profile API에서 Group,Favorite API 분리, 토큰 인증 처리 추가
---
- Profile API 에서 Group API, Favorite API 분리
- GroupAPI, Favorite API 토큰 인증 처리 추가
- Group, Favorite 예외 분리
- 다른 사용자의 정보를 수정, 삭제하지 못하도록 조건 예외 처리
- JWT 환경변수 못불러오는 문제 수정
- 일부 코드 가독성 향상 위해 들여쓰기 추가
---
> 프로필 API 분리 
> 그룹 API 분리
> 즐겨찾기 API 분리
와  !! 깔끔하다!!! 
---
---
PostMan, SwaggerUI
---
- 이전보다.. 보기 편할겁니다
---
> Ref/favorite auth Profile API에서 Group,Favorite API 분리, 토큰 인증 처리 추가

- src/main/java/com/even/zaro/controller/S3Controller.java
- src/main/java/com/even/zaro/service/S3Service.java
- post 이미지 업로드 시 postId 생성 전 이미지 업로드로 postId 삭제
---
- post 이미지 업로드 시 postId 생성 전 이미지 업로드로 서비스, 컨트롤러에서 postId 삭제
- 스웨거 반영
---
---
---
---
- 오전 프론트 요청으로 수정합니다.
- post도 카테고리로 구분해볼까 하다가, 프론트에서 단순하게 처리하는 게 좋을 것 같다는 의견과, 시연시 게시물이 그렇게 많지 않고 사용자가 많아진 후에(상상 속?) 구분해보는 것도 나쁘지 않을 것 같다는 의견입니다.
---
- [노션](https://www.notion.so/nahyuk/presigned-url-1f47ef37c243802e87b9d4e6a44e05d3)
> Hotfix/presigned-url post 이미지 업로드 시 postId 생성 전 이미지 업로드로 postId 삭제

- src/main/java/com/even/zaro/controller/GroupController.java
- src/main/java/com/even/zaro/dto/group/GroupCreateRequest.java
- src/main/java/com/even/zaro/dto/group/GroupEditRequest.java
- src/main/java/com/even/zaro/dto/group/GroupResponse.java
- src/main/java/com/even/zaro/entity/FavoriteGroup.java
- src/main/java/com/even/zaro/service/GroupService.java
- Group API 관련 @Data 남용 문제 수정
---
- /dto/profile 에 있던 group 요청, 응답 객체 /dto/group 으로 이동
- @Data 어노테이션 삭제
- 업데이트가 필요한 필드에 대해서 엔티티에 메서드 추가
---
---
---
---
- 이전에 나현님이 남겨줬던 @Data 남용문제 해결
- 지은님 코드 리뷰 진행하며 다시 각인됐습니다 @Data를 남발하지 않도록 하겠습니다. . 
---
> Ref/group @Data 어노테이션 관련 리팩토링

- src/main/java/com/even/zaro/entity/Favorite.java
- src/main/java/com/even/zaro/entity/Place.java
- src/main/java/com/even/zaro/global/ErrorCode.java
- src/main/java/com/even/zaro/repository/FavoriteRepository.java
- src/main/java/com/even/zaro/service/FavoriteService.java
- favorite API @Data 관련 리팩토링 및 중복 즐겨찾기 추가 문제 수정
---
- favorite API의 @Data 삭제 후 @Setter 사용
- 적절히 메소드를 엔티티에 생성 후 사용하도록 수정
- 즐겨찾기 중복 추가 문제 수정
- 
---
---
---
- SwaggerUI
---
- 
---
- 관련 이슈 번호: `close #123`
- 기획서, 디자인, API 문서 등 첨부
> ref/favorite 즐겨찾기 API 리팩토링

- src/main/java/com/even/zaro/config/security/SecurityConfig.java
- src/main/java/com/even/zaro/controller/ProfileController.java
- 기본정보조회 외의 profile api에 로그인 인증추가
---
- profile 컨트롤러의 getUserProfile제외한 모든 메서드에 인증 추가
- SecurityConfig 에서 getUserProfile 엔드포인트만 인증해제 설정
- Swagger 문서화 코드 수정
---
> Swagger 프로필 api들 인증 추가된 부분
> 인증 필요 api에 인증토큰 전달하지 않았을 때 (403에러)
> 인증 필요 api에 인증토큰 전달할 경우 (성공)
> 프로필 기본정보 조회 메서드는 로그인 유무 관계없이 작동합니다 (성공)
---
---
---
> Ref/profile : 기본정보조회 외의 profile api에 로그인 인증추가

- src/main/java/com/even/zaro/dto/group/GroupCreateRequest.java
- src/main/java/com/even/zaro/dto/group/GroupEditRequest.java
- src/test/java/com/even/zaro/group/GroupAPITest.java
- GroupAPI의 기능들의 성공 테스트 케이스 생성
---
- 일부 추가, 수정 요청 객체의 @Data 어노테이션 삭제 후 @Setter로 변경
- 요청 객체에 @Builder 추가
- GroupAPI의 성공 테스트 케이스 작성 완료
---
> ![image](https://github.com/user-attachments/assets/f2e0bd9b-836c-4d56-b12f-e04c77923ee8)
- 성공 테스트 케이스 모두 통과
---
---
---
- 예외 케이스는 따로 이슈파서 새로 pr 날리도록 하겠습니다
한 pr에 너무 많은 테스트 케이스를 작성하면 리뷰하기 힘들것 같아서용
- 그리고 한글 메서드 이름을 사용한 이유는 직관적이기도 하고 배민, 토스 등에서 테스트 케이스를 작성할 때는 
많이 사용한다고 하여 한번 사용헤봤습니다~~
---
- close #32
> Test/group 성공 테스트 케이스 작성

- src/main/java/com/even/zaro/dto/group/GroupCreateRequest.java
- src/main/java/com/even/zaro/dto/group/GroupEditRequest.java
- src/main/java/com/even/zaro/global/exception/group/GroupException.java
- src/main/java/com/even/zaro/service/GroupService.java
- src/test/java/com/even/zaro/group/GroupAPITest.java
- Group API 예외 테스트 케이스 작성
---
- Group API 에서 발생할 수 있는 주요 예외 테스트 케이스 작성
- 기존 그룹 리스트 조회 시 조회 결과가 빈 배열이면 예외를 던지지 않던 문제 수정
- 필요한 부분 @Builder 추가
---
> ![image](https://github.com/user-attachments/assets/30e70a67-cd00-494d-acf6-b9d57b01e287)
- 테스트 모두 성공
---
---
---
- 그룹 API 관련 테스트 케이스 모두 작성 완료했습니다.
---
- close #37
> Test/group-exception 그룹 API 예외 테스트 케이스 

- src/main/java/com/even/zaro/controller/AuthController.java
- src/main/java/com/even/zaro/dto/auth/KakaoSignInRequestDto.java
- src/main/java/com/even/zaro/dto/auth/KakaoUserInfoDto.java
- src/main/java/com/even/zaro/entity/User.java
- src/main/java/com/even/zaro/global/ErrorCode.java
- src/main/java/com/even/zaro/repository/UserRepository.java
- src/main/java/com/even/zaro/service/AuthService.java
- src/main/java/com/even/zaro/service/KakaoOAuthService.java
- 카카오 로그인 API 구현
---
- 카카오 로그인 API 구현
- 일반 로그인, 카카오 로그인 토큰 발급 및 유저 response 빌드 부분 별도 메서드로 분리
- 일반 회원가입시 default profile image 저장되는 부분 삭제 -> Null일 경우 프론트에서 처리
---
토큰 정보 잘못 됐을 때
---
---
---
- User 테이블에 profile_image 부분이 제 db에 not null로 되어 있더라구요! 혹시나 이러신 분들 이번에 에러날 수도 있으니 에러가 나신다면 alter table 에서 not null 없애 주시면 되겠습니다. 에러 안나면 패스.
```sql
ALTER TABLE `evenfinal`.`user` 
CHANGE COLUMN `profile_image` `profile_image` VARCHAR(255) NULL ;
```
---
> Feat/social login 카카오 로그인 API 구현

- src/main/java/com/even/zaro/dto/favorite/FavoriteAddRequest.java
- src/main/java/com/even/zaro/dto/favorite/FavoriteEditRequest.java
- src/test/java/com/even/zaro/favorite/FavoriteApiTest.java
- FavoriteAPI 성공 테스트 케이스 추가
---
- 그룹에 즐겨찾기 추가 성공 테스트 케이스 추가
- 즐겨찾기 메모 수정 성공 테스트 추가
- 즐겨찾기 리스트 조회 성공 테스트 추가
- 즐겨찾기 삭제 성공 테스트 케이스 추가
- 필요한 dto @Data -> @Getter, @Builder 추가
---
> ![image](https://github.com/user-attachments/assets/f31d416d-897b-47e3-87c5-3fba055f977e)
- 성공 테스트 케이스 모두 테스트 완료
---
- [] log.info / 불필요한 주석 제거
---
---
---
- close #33
> Test/favorite Favorite API 성공 테스트 케이스 추가

- src/main/java/com/even/zaro/dto/auth/SignUpRequestDto.java
- src/main/java/com/even/zaro/entity/Comment.java
- src/main/java/com/even/zaro/entity/FavoriteGroup.java
- src/main/java/com/even/zaro/entity/Post.java
- src/main/java/com/even/zaro/entity/User.java
- src/main/java/com/even/zaro/global/ErrorCode.java
- src/main/java/com/even/zaro/global/scheduler/TokenCleanupScheduler.java
- src/main/java/com/even/zaro/repository/UserRepository.java
- src/main/java/com/even/zaro/service/AuthService.java
- src/test/java/com/even/zaro/service/AuthServiceTest.java
- 닉네임 중복 가능 -> 불가 엔티티, 서비스 로직 수정
---
- 닉네임 중복 가능 -> 불가 엔티티, 서비스 로직 수정
- @Builder.Default warning 해결
- 이메일 토큰 삭제 스케줄러 오류 수정
- 어제 새벽 스케줄러 작동 안함 확인(스케줄러에서 JPA delete 실행 중 트랜잭션이 없어서 실패) -> 트랜잭션 추가
---
---
---
- nickname 중복 시 예외 처리 발생
---
- 댓글 태그 문제로 닉네임 중복 가능에서 중복 불가로 변경
---
> Fix/user nickname unique 

- src/test/java/com/even/zaro/integration/AuthServiceIntegrationTest.java
- src/test/java/com/even/zaro/service/AuthServiceTest.java
- 단위테스트 및 통합테스트 구분
---
- 기존에 작성한 닉네임 중복 로직 단위테스트 및 통합테스트 구분
---
---
---
---
- 제가 이전에 스케줄러 로직 테스트할 때 db(테스트용 h2)를 사용한다고(스케줄러 로직 자체가 db에서 삭제 되는지 테스트하는 것이라..) SpringBootTest를 했었는데 이게 통합 테스트할 때 사용하는 거라고 하더라구요.
- 이번에는 (회원 가입시 닉네임 중복 예외처리) 단순히 서비스 단의 로직 검증용이어서 사실 db까지 쓸 필요 없이 Mock으로 단위테스트만 진행했으면 되는데.. (아주 빠름) 이 사실을 모르고 db 사용하는 테스트를 해버렸습니다. 
- 이번에 기록용으로 구분해서 올리게 되었습니다.
- db 사용하는 테스트 진행시 패키지를 integration 만들었으니 여기에 넣으시면 될 것 같습니다. (자세히 모름. 혹시 자세하고 제대로된 정보 알게 되면 공유 바랍니다.)
---
- 디코 정보 방에 블로그 하나 남겼으니 참고 바랍니다.
> Fix/authservice unit test 단위테스트 및 통합테스트 구분

- src/main/java/com/even/zaro/controller/NotificationController.java
- src/main/java/com/even/zaro/entity/Notification.java
- src/main/java/com/even/zaro/global/ErrorCode.java
- src/main/java/com/even/zaro/global/exception/notification/NotificationException.java
- src/main/java/com/even/zaro/global/scheduler/NotificationCleanupScheduler.java
- src/main/java/com/even/zaro/repository/NotificationRepository.java
- src/main/java/com/even/zaro/service/NotificationService.java
- 알림 개별 읽기 api, 알림 전체읽기 api, 알림 자동삭제 스케줄링 구현
---
- 새로 생성 된 파일 없습니다 (기존의 Notification 파일들 내부에서 구현)
- 스케줄링은 기존의 SchedulingConfig로 이미 설정 되어있어서, 구현메서드에 @Scheduled 붙여서 사용했습니다
---
- 알림 개별 읽기 api (로그인 필요)
> ![image](https://github.com/user-attachments/assets/c9815579-bb86-465c-aba3-b76d32599cba)
- 알림 전체 읽기 api (로그인 필요)
> ![image](https://github.com/user-attachments/assets/dc3c65e1-c8d5-4cd8-af1d-05331c3f4866)
- 생성된 지 30일 이상 지난 알림 자동삭제 스케줄링
- 서버시간을 30일 후로 넘기는 것은 너무 헤비한 테스트 방법인지라... 코드를 아래처럼 수정한 후 테스트 진행했습니다
**스케줄러 도는 주기 : 매일 새벽 3시 실행 -> (테스트용) 매 분 실행
deletingDate : 현재시각보다 30일 전 -> (테스트용) 현재 시각보다 5분 전** 
> 1️⃣ DB 초기 상태
> 2️⃣ 스케줄러 1차 실행 후 DB : 하루 전에 생성된 알림==스케줄러 실행시각 5분전 보다 전 -> 삭제됨
> 3️⃣ 나머지 알림들 생성시각보다 5분 지난 후, 가장 첫번째 스케줄러 실행 로그 & DB
---
---
---
> Feat/notification : 알림 개별 읽기 api, 알림 전체읽기 api, 알림 자동삭제 스케줄링 구현

- src/main/java/com/even/zaro/controller/CommentController.java
- src/main/java/com/even/zaro/dto/PageResponse.java
- src/main/java/com/even/zaro/dto/comment/CommentResponseDto.java
- src/main/java/com/even/zaro/service/CommentService.java
- 댓글 리스트 조회 API 구현 및 공통 page response 추가
---
- 댓글 리스트 조회 API 구현
- 공통 page response 추가
- 오후에 프론트와 논의 결과 content, totalPages, number 를 내려주기로 했습니다.
---
---
---
---
- 
---
- 관련 이슈 번호: #54 - 리팩토링 방법 댓글로 작성해놓겠습니다.
> Feat/comment r 댓글 리스트 조회 API 구현 및 공통 page response 추가

- src/main/java/com/even/zaro/controller/CommentController.java
- src/main/java/com/even/zaro/dto/PageResponse.java
- src/main/java/com/even/zaro/dto/comment/CommentRequestDto.java
- src/main/java/com/even/zaro/dto/comment/CommentResponseDto.java
- src/main/java/com/even/zaro/entity/Comment.java
- src/main/java/com/even/zaro/global/ErrorCode.java
- src/main/java/com/even/zaro/repository/CommentRepository.java
- src/main/java/com/even/zaro/repository/PostRepository.java
- src/main/java/com/even/zaro/service/CommentService.java
- 댓글 수정 및 삭제 API 
---
- 댓글 수정 및 삭제 API 
- 댓글 생성, 수정 시 댓글 내용 없음 예외처리 추가
---
댓글 수정
댓글 작성자 아님 예외
댓글 삭제
댓글 작성자 아님 예외
댓글 내용 없음 예외
---
---
---
- 브랜치 따는 거 깜빡해서.. 이전 pr과 같은 브랜치 입니다.  `add: 댓글 커스텀 에러코드 추가` 커밋부터 작업.
- 지금 생성, 수정, 리스트 응답 모두 같은 dto 사용하고 있는데 프론트에서 어떻게 작업하실지 몰라서 일단은 모든 응답을 동일하게 다 내렸습니다.
- 프론트에서 생성, 수정 후 리스트 다시 조회하지 않고 해당 댓글만 랜더링 하는 쪽으로 간다면 변경되는 것은 없습니다.
- 이후 생성, 수정 후 리스트를 다시 조회한다면 생성, 수정시 commentId만 내려주는 걸로 응답 축소할 예정입니다.
---
> Feat/comment ud 댓글 수정 및 삭제 API 

- src/main/java/com/even/zaro/config/QueryDslConfig.java
- src/main/java/com/even/zaro/controller/MapController.java
- src/main/java/com/even/zaro/dto/map/PlaceResponse.java
- src/main/java/com/even/zaro/global/ErrorCode.java
- src/main/java/com/even/zaro/repository/MapQueryRepository.java
- src/main/java/com/even/zaro/service/MapService.java
- 좌표기반 인근 장소 조회 API 구현
---
- 에러 코드 추가 : BY_COORDINATE_NOT_FOUND_PLACE_LIST (조회된 장소가 없을 때)
- QueryDsl 설정 파일 추가
- 위도, 경도, 거리를 입력 받아 인근 장소리스트를 조회하는 API 구현
- PlaceResponse DTO 생성
---
> ![image](https://github.com/user-attachments/assets/736cf444-b509-423f-b346-9d302818d14f)
- 예제 Place 테이블 데이터 세팅 
> ![image](https://github.com/user-attachments/assets/3f945030-e056-4203-87f0-f83885035537)
- 서울역 좌표(37.554722, 126.970833) 기준으로 1Km 내 장소 조회 결과 (2개 조회)
- 조회된 장소의 개수와 장소 리스트들이 응답 ( totalCount는 이번에 추가했습니다 액셀 반영완료)
> ![스크린샷 2025-05-22 오후 4 49 36](https://github.com/user-attachments/assets/73185007-9b4d-46cf-b2ea-8c241b78869c)
- 서울역 좌표(37.554722, 126.970833) 기준으로 2Km 내 장소 조회 결과 (8개 조회)
> ![image](https://github.com/user-attachments/assets/38b8b775-2281-4aaf-95ae-76b458496e2c)
- 아예 떨어져있는 의정부의 …
> Feat/by-cordinate-list 좌표기반 인근 장소 조회 API 구현

- src/main/java/com/even/zaro/controller/CommentController.java
- src/main/java/com/even/zaro/dto/comment/CommentRequestDto.java
- src/main/java/com/even/zaro/dto/comment/CommentResponseDto.java
- src/main/java/com/even/zaro/dto/comment/MentionedUserDto.java
- src/main/java/com/even/zaro/entity/Comment.java
- src/main/java/com/even/zaro/global/ErrorCode.java
- src/main/java/com/even/zaro/repository/UserRepository.java
- src/main/java/com/even/zaro/service/CommentService.java
- 댓글 생성 API 수정(답글 달기 기능 추가)
---
- 댓글 생성 API 수정(답글 달기 기능 추가)
- 댓글 엔티티 taggedUser -> mentionedUser 수정 (서버 반영 후 db column 삭제 하겠습니다.)
- 일반 댓글 및 답글 api 엔드포인트 동일합니다. body에 mentionedNickname 유무로 구분
- 일반 댓글의 경우 mentionedNickname 값이 null, "", 아예 필드 없음 다 가능합니다. 전부 null로 들어감.
---
|답글일 경우 | 일반 댓글의 경우(답글이 아님) | 
|-----------|-----------|
|![image](https://github.com/user-attachments/assets/81ef0a10-f959-4062-afcc-06660f60807e)|![image](https://github.com/user-attachments/assets/b1ae8b47-6fba-43f2-9472-e9010090f2c6)|
리스트 조회시 mentionedUser 추가
---
- 멘션한 사용자 없음 예외 
---
---
- 
---
- 관련 이슈 번호: `close #123`
- 기획서, 디자인, API 문서 등 첨부
> Feat/comment reply tag 답글 달기 기능 추가

- src/main/java/com/even/zaro/controller/FavoriteController.java
- src/main/java/com/even/zaro/controller/GroupController.java
- src/main/java/com/even/zaro/dto/group/GroupCreateRequest.java
- src/main/java/com/even/zaro/dto/group/GroupEditRequest.java
- src/main/java/com/even/zaro/dto/group/GroupResponse.java
- src/main/java/com/even/zaro/global/ErrorCode.java
- src/main/java/com/even/zaro/service/FavoriteService.java
- src/main/java/com/even/zaro/service/GroupService.java
- 즐겨찾기 API 리팩토링 
---
- 필요없는 주석 제거
- 예외 코드 추가
- 스웨거 액셀과 통일
- id, name 등 placeId, placeName 처럼 명확히 수정
- 토큰 인증 처리 로직 추가
---
- 정상 동작합니다.
---
---
---
- 이전 PR에는 언급 안했는데 프론트에서 id 값을 받을 때 그냥 id 보다는 placeId 같이 무슨 데이터의 id인지 나타나면 
더 명확한 느낌이 있어서 리팩토링 진행시 참고만? 부탁드립니다~~~
- 즐겨찾기 추가 API 관련해서 미처 구현하지 못했던 부분이 있어서 이슈 새로 파놨습니다. #70 
이번 pr에는 반영 못할 것 같고, 추후 pr에 해당 이슈 태그하여 해결하도록 하겠습니다.
---
- close #69 
- #70
> Ref/favorite 즐겨찾기 API 리팩토링 

- src/main/java/com/even/zaro/controller/FavoriteController.java
- src/main/java/com/even/zaro/controller/GroupController.java
- src/main/java/com/even/zaro/dto/favorite/FavoriteAddRequest.java
- src/main/java/com/even/zaro/global/ErrorCode.java
- src/main/java/com/even/zaro/repository/PlaceRepository.java
- src/main/java/com/even/zaro/service/FavoriteService.java
- 즐겨찾기 추가 API 에서 해당 장소가 DB에 등록이 안되어있을 때 새로 DB에 장소를 저장하는 로직 추가
- 이미 등록되어있다면 기존 장소를 즐겨찾기에 추가
---
- 요청 객체 필드 추가 및 @Schema 추가 (장소를 저장하기 위해)
---
> ![image](https://github.com/user-attachments/assets/cf1857a1-6de0-4f48-b5a0-66050e19536c)
> ![image](https://github.com/user-attachments/assets/21a3ef60-d8cd-428d-a47a-d71dc869a07c)
- 이미  즐겨찾기가 추가되어있을 때 요청 및 응답
> ![image](https://github.com/user-attachments/assets/7ab7d463-09ec-455b-8eb6-8bf6fb9f1e26)
> ![image](https://github.com/user-attachments/assets/058f9cf6-396b-465d-b0de-90fa6eb83432)
- 즐겨찾기가 등록되어있지 않았을 때 요청 및 응답
-> API 테스트 문제 X
---
---
---
- 이미 추가한 즐겨찾기에 대해서는 다른 그룹에 추가 불가능하게 작성되어있습니다~
디스코드에서 얘기했다싶이 같은 장소에 대해서 한 유저가 여러 메모가 추가될 우려가 있기 때문!!
---
- close #70
> Ref/favorite-add-place 즐겨찾기 추가 API 리팩토링

- src/main/java/com/even/zaro/repository/PostRepository.java
- src/main/java/com/even/zaro/service/PostService.java
- 게시글 상세 페이지 조회할 때 500 오류 문제 해결
---
- 게시글 상세 페이지 조회할 때 500 오류 문제 해결
- 오류 : Unable to locate Attribute with the given name [imageUrlList] on this ManagedType [com.even.zaro.entity.Post]"
- image url 부분 수정시 PostRespository에 @EntityGraph 부분 코드를 수정하지 않아 발생한 오류입니다. (Post + post_image 테이블을 join해서 한 번에 데이터 가져오는 코드)
- 위와 별개로 변수명 하나 수정했습니다~ 
---
---
---
---
- 프론트 요청사항입니다.
---
> Hotfix/image url db 에러 해결

- src/main/java/com/even/zaro/entity/Notification.java
- src/main/java/com/even/zaro/global/exception/notification/NotificationException.java
- src/main/java/com/even/zaro/global/scheduler/NotificationCleanupScheduler.java
- src/test/java/com/even/zaro/global/scheduler/NotificationCleanupSchedulerTest.java
- src/test/java/com/even/zaro/notification/notificationApiTest.java
- 알림 기능 성공/예외 통합 테스트코드 구현
---
- NotificationException 에 Getter, errorCode 필드추가
- 알림 기능별 성공 테스트 코드 구현
- 알림 기능별 실패 테스트 코드 구현
- 알림 30일후 자동삭제 스케줄러 테스트 코드 구현
---
> 알림 기본 기능 : 3개의 성공케이스, 1개의 실패케이스 테스트 성공
> 알림 30일 후 자동삭제 스케줄러 테스트
- 사진처럼 Notification 엔티티, created_at 컬럼의 @CreationTimeStamp 주석처리해야 정상통과됩니다
(알림 생성시각 자동주입코드 삭제 필요)
---
---
---
- listener를 이용한 알림 생성의 테스트는 예정사항입니다 !
---
> Test/notification : 알림 기능 성공/예외 통합 테스트코드 구현

- .env.dev.example
- .env.local.example
- .env.prod.example
- build.gradle
- docker-compose.dev.yml
- docker-compose.prod.yml
- src/main/java/com/even/zaro/config/ElasticsearchConfig.java
- src/main/java/com/even/zaro/config/security/SecurityConfig.java
- src/main/java/com/even/zaro/controller/PostSearchController.java
- src/main/java/com/even/zaro/elasticsearch/ReindexController.java
- src/main/java/com/even/zaro/elasticsearch/document/PostEsDocument.java
- src/main/java/com/even/zaro/event/PostDeletedEvent.java
- src/main/java/com/even/zaro/event/PostSavedEvent.java
- src/main/java/com/even/zaro/global/ErrorCode.java
- src/main/java/com/even/zaro/listener/PostDeletedEventListener.java
- src/main/java/com/even/zaro/listener/PostSavedEventListener.java
- src/main/java/com/even/zaro/service/PostEsSearchService.java
- src/main/java/com/even/zaro/service/PostSearchService.java
- src/main/java/com/even/zaro/service/PostService.java
- src/main/resources/application.yaml
- Elasticsearch 적용 검색 API 구현
---
- Elasticsearch 적용 검색 API 구현
- eventlistener을 통해 게시글 작성시 db 저장 후 es 저장 실행 
- 게시글 수정시 db 수정 후 es 수정(같은 postId 덮어쓰기)
- 게시글 삭제시 db 수정 후 es에서 아예 삭제
- title, content 검색
- 오타 허용(어느 정도..만 fuzzy 사용)
- 다중 키워드 순서 상관 없음("자취 꿀템", "꿀템 자취")
- 분석기 nori_only 적용 (한국어 형태소 분석) - 이 부분은 kibana 툴 이용해서 인덱스 생성시 적용(postman도 가능)
- 인덱스 설정 변경시 인덱스 삭제 후 재 생성해야 하는데 이때 사용할 개발용 /api/es/reindex 리인덱스 api 만들었습니다.
- DB(post) 전체가 ES 인덱스로 저장되는 API 입니다.  (isDeleted true인 row는 들어가지 않습니다.)
---
|게시글 생성 시 같이 저장되는 es 인덱스 | DB 비교 |
|-----|----|
|![image](https://github.com/user-attachments/assets/f04cde1f-e401-4f4e-8a96-f67fec2924d2)|![image](https://github.com/user-attachments/assets/a5da7c6d-25e2-4285-9652-e353c764cb2f)|
|오타 가능| 다중 키워드 부분 검색 x, 순서 상관 없음 |
|--------|--------| …
> Feat/search es Elasticsearch 적용 검색 API 구현

- src/main/java/com/even/zaro/dto/post/PostPreviewDto.java
- 리스트조회시 content 자르는 부분 삭제!
---
> 
| 기존 | 수정 후 |
|-----|-----|
|<img width="1624" alt="스크린샷 2025-05-27 오후 6 12 56" src="https://github.com/user-attachments/assets/26f72148-3d8a-444e-82fd-758bbca0d907" />|<img width="1624" alt="스크린샷 2025-05-27 오후 6 11 18" src="https://github.com/user-attachments/assets/7b067216-91fe-4516-98e2-1d5867b8d558" />|
> ref: 리스트조회 content 자르는거 수정

- src/main/java/com/even/zaro/elasticsearch/document/PostEsDocument.java
- es 저장시 content 이미지 url, html, 여러 줄바꿈 생략
---
- es 저장시 content 이미지 url, html, 여러 줄바꿈 생략
- 기능 변화는 없습니다.
서버에 아래 사진과 같이 content에 이미지 마크다운까지 저장이 되어서.. 이 부분 생략하고 es에 저장하도록 했습니다. -> 이미지로 검색시.. 나옴 ㅠㅠ
수정 후 
---
---
---
---
> fix: es 저장시 content 이미지 url, html, 여러 줄바꿈 생략

- src/main/java/com/even/zaro/controller/ProfileController.java
- src/main/java/com/even/zaro/service/ProfileService.java
- 프로필 기능 내 공통 Page 응답 dto 리팩토링
---
- 기존 페이지네이션 -> 공통 PageResponseDto 사용코드로 변경
- 기능 특성에 맞게 DESC로 최신순 정렬(내림차순) 사용했습니다 ~
`@PageableDefault(size = 10, sort = "createdAt", direction = Sort.Direction.DESC)`
---
> 유저가 쓴 게시물 list 조회
> 유저가 좋아요 누른 게시물 list 조회
> 유저가 쓴 댓글 list 조회
- 데이터가 없는 것은 로컬DB에 데이터가 없어서일 뿐 이전과 같이 잘 작동됩니다~!
---
---
---
- 머지할 때 Issue close 걸어두겠습니다 :) ~ approve시 확인코멘트 남겨주세용
---
- 관련 이슈 번호: close #54
> Ref/page response : 프로필 기능 내 공통 Page 응답 dto 리팩토링

- src/test/java/com/even/zaro/profile/ProfileApiTest.java
- 변경된 getUserPosts메서드 리턴타입에 맞게 testCode 수정
---
- 유저가_쓴_게시물_목록_조회_성공() 테스트 메서드 내부, getUsersPost호출 코드 최신에 맞게 수정
---
> 빨간 줄 제거됨, 수정된 케이스 포함한 다시 전체 테스트케이스 정상 통과됨
---
---
---
- 프로필 기능 내 공통 Page 응답 dto 리팩토링 이후, TestCode는 수정하지 않아서 뜬 오류..
- 변경사항 있을 경우 testCode도 잊지않고 같이 수정하도록 해야겠습니다, 알려주신 @nahyukk 께 Thanks를...💗
---
- 관련 이슈 번호: #91
> fix/profile-test : 변경된 getUserPosts메서드 리턴타입에 맞게 testCode 수정

- src/main/java/com/even/zaro/controller/UserController.java
- src/main/java/com/even/zaro/dto/profile/UserProfileDto.java
- src/main/java/com/even/zaro/dto/user/UpdateProfileRequestDto.java
- src/main/java/com/even/zaro/dto/user/UpdateProfileResponseDto.java
- src/main/java/com/even/zaro/dto/user/UserInfoResponseDto.java
- src/main/java/com/even/zaro/entity/Gender.java
- src/main/java/com/even/zaro/entity/Mbti.java
- src/main/java/com/even/zaro/entity/User.java
- src/main/java/com/even/zaro/service/AuthService.java
- src/main/java/com/even/zaro/service/UserService.java
- src/test/java/com/even/zaro/service/UserServiceTest.java
- 프로필(계정정보) 변경 API
---
- 프로필(계정정보) 변경 API
- gender, mbti enum으로 변경
---
---
---
- 성공
- 전체 변경
- 부분 변경 (부분 null)
- userId 예외
- status PENDING 예외
---
- enum 변경으로 기존 로직 중 변경해야 하는 부분 같이 변경했습니다.
- UserProfileDto MBTI enum 으로 수정 @yoorym-kim 
- 카카오 로그인 - 성별 enum 수정
- 내정보조회 dto - 성별, mbti enum 수정
---
> Feat/update profile 프로필(계정정보) 변경 API

- src/main/java/com/even/zaro/repository/CommentRepository.java
- src/main/java/com/even/zaro/service/CommentService.java
- 댓글 리스트 조회 desc, asc 변동 안되는 버그 수정
---
- 댓글 리스트 조회 desc, asc 변동 안되는 버그 수정 
- repository 메서드 문제
---
desc
asc
---
---
---
- 프론트에서 버그 발견해주셨습니다.
---
> fix: 댓글 리스트 조회 desc, asc 변동 안되는 버그 수정 - repository 메서드 문제

- src/main/java/com/even/zaro/controller/UserController.java
- src/main/java/com/even/zaro/dto/user/UpdateProfileImageRequestDto.java
- src/main/java/com/even/zaro/dto/user/UpdateProfileImageResponseDto.java
- src/main/java/com/even/zaro/entity/User.java
- src/main/java/com/even/zaro/service/UserService.java
- src/test/java/com/even/zaro/service/UserServiceTest.java
- 프로필 이미지 변경 API
---
- 프로필 이미지 변경 API
---
---
---
- 성공
- userId 예외
- status PENDING 예외
---
---
> Feat/update profile image 프로필 이미지 변경 API

- Jenkinsfile
- 젠킨스 파이프라인 수정 : 무중단, 자동 배포 스크립트
---
- 젠킨스 파이프라인 수정
- 무중단, 자동 배포 스크립트 적용
---
- t2.small(메모리 2G) 서버(편의상 B 서버)를 하나 더 열었습니다.
- 젠킨스파일 stage 보시면 아시겠지만 A에서 빌드 up 될 동안 프록시를 B서버로 옮긴 후, A 서버에서 git pull, 이미지 빌드, 컨테이너 실행을 한 후, 다시 프록시를 A로 옮겨서 새로 배포된 기능을 사용할 수 있도록 했습니다. 그 이후 A 서버의 이미지를 B서버로 복사 하고 B에서도 실행시켜서 A에 문제가 생길 때 또는 다음 빌드 시에 B 서버로 api 사용할 수 있도록 했습니다.
---
- 웹훅 너무 많은 것 같아서 에러가 날 때만 메시지 주도록 수정했습니다.
- 젠킨스 서버에 올려서 개인별로 사용(테스트? 놀기..?ㅎ)하실 수 있도록 디코에 id password 공유드리겠습니다!
---
> fix: 젠킨스 - 무중단, 자동 배포 스크립트

- src/main/java/com/even/zaro/dto/notification/NotificationDto.java
- src/main/java/com/even/zaro/entity/Notification.java
- src/main/java/com/even/zaro/global/ErrorCode.java
- src/main/java/com/even/zaro/jwt/JwtAuthFilter.java
- src/main/java/com/even/zaro/jwt/JwtUtil.java
- src/main/java/com/even/zaro/listener/CommentListener.java
- src/main/java/com/even/zaro/listener/FollowListener.java
- src/main/java/com/even/zaro/listener/PostLikeListener.java
- src/main/java/com/even/zaro/service/NotificationService.java
-  알림 응답 DTO 확장, Notification 엔티티에 컬럼추가
---
- extractTokenFromCookies 메서드 jwtUtil로 이동, public 전환
- 리뷰 반영 #90 
- FE ui 디자인에 따른, 알림 응답 DTO에 정보 추가
- 액터유저 (알림 유발 유저) 정보 (id, username, profileImage)
- 게시물 좋아요 & 댓글 알림 : 게시물 정보 (thumbnail, postId)
- 댓글 알림 : 댓글 정보 (comment.content)
- Notification 엔티티에 actorUserId 컬럼 추가
- 컬럼추가는 피해보려 했지만, 없을 경우 게시물 좋아요 알림에서 특히 불필요 join 너무 많았습니다
---
> 알림 List 조회 시 변경된 응답형식 확인 가능
---
---
- swagger와 로컬서버 ui를 통한 알림 생성 (댓글 쓰기, 좋아요 누르기, 팔로우하기)
- swagger에서 알림조회 응답형식 확인 !
---
---
> Ref/sse notification : 알림 응답 DTO 확장, Notification 엔티티에 컬럼추가

- src/main/java/com/even/zaro/config/security/SecurityConfig.java
- src/main/java/com/even/zaro/controller/PostController.java
- src/main/java/com/even/zaro/dto/post/PostRankResponseDto.java
- src/main/java/com/even/zaro/entity/Post.java
- src/main/java/com/even/zaro/repository/PostRepository.java
- src/main/java/com/even/zaro/service/CommentService.java
- src/main/java/com/even/zaro/service/PostLikeService.java
- src/main/java/com/even/zaro/service/PostService.java
- 인기게시글 API 구현
---
- 삭제된 게시글 미포함
- 인기 게시글 조회시 score순으로 상위 10개 정렬 후 반환
- **score 기준** ⬇️
-  좋아요 (likeCount) **3점** + 댓글 수 (commentCount) **5점**
- score 가 동점일때 -> 최신글 우선으로 정렬
---
> 
| 인기글 조회 | DB | 스웨거 |
|-------|-------|-------|
|![스크린샷 2025-05-30 오후 9 23 27](https://github.com/user-attachments/assets/1b649841-8a2b-43f9-903a-a41f7557d84c)|<img width="1012" alt="스크린샷 2025-05-30 오후 9 22 57" src="https://github.com/user-attachments/assets/17932d53-af8f-4008-952f-bbf87e18de3c" />|![스크린샷 2025-05-30 오후 9 34 48](https://github.com/user-attachments/assets/575bca1b-d99e-4191-b41a-645df08ac71b)|
---
- 조회수를 추가할까 하다가 조작이 쉬운점과 조회만으로 관심도를 판단하기 어렵다 생각이들어 좋아요수와 댓글수로 기준을 잡았습니다.
> Feat/rank : 실시간 인기 게시글 API 구현

- src/main/java/com/even/zaro/service/UserService.java
- src/test/java/com/even/zaro/service/UserServiceTest.java
- UserService 책임분리
---
- 빼먹은 Transactional :)
- UserService 공통 검증 메서드 추출
---
---
---
- 공통 메서드 단위테스트 추가했습니다. FindByIdUserNotExists, validateNotPending 
- 기존 코드는 굳이 지우지는 않았습니다.
---
- 이슈 #112 참고 부탁드립니다. 다른 서비스에서 많이 사용되는 검증 메서드 인것 같습니다.
---
- 이슈 : Fixes #112
> Fix/code reviewed UserService 책임분리

- src/main/java/com/even/zaro/dto/favorite/FavoriteAddRequest.java
- src/main/java/com/even/zaro/dto/map/MarkerInfoResponse.java
- src/main/java/com/even/zaro/dto/map/PlaceResponse.java
- src/main/java/com/even/zaro/entity/Category.java
- src/main/java/com/even/zaro/entity/Place.java
- src/main/java/com/even/zaro/service/FavoriteService.java
- src/main/java/com/even/zaro/service/MapService.java
- 지도 API에서 즐겨찾기 추가 또는 장소데이터를 응답할 때, category 값을 함께 전송 또는 응답 받도록 수정했습니다.
---
- Place 테이블 category 필드 추가 (만약 null값일시 디폴트 ETC로 저장)
- 요청, 응답 dto에 category 필드 추가
---
> ![image](https://github.com/user-attachments/assets/596b8274-b4bf-4e70-92de-3d5a1d336792)
- 즐겨찾기 추가 API 요청객체에 카테고리 필드 추가, 정상 동작 확인
> ![image](https://github.com/user-attachments/assets/8aa3fc06-db39-4632-a0d8-534877b4898f)
> ![image](https://github.com/user-attachments/assets/c4713fbb-177b-43c3-8570-e2a7055f2272)
- 인근맛집 조회 API 요청 및 응답에 정상적으로 category 필드 포함
> ![image](https://github.com/user-attachments/assets/69ba13fd-616f-45ff-b428-cd0f3b75be9d)
- 장소의 메모리스트와 정보 조회API 에 카테고리 필드 정상 응답
---
---
---
- 
---
- close #99
> Ref/map 지도 API 장소 테이블에 category 필드 추가 

- build.gradle
- src/main/java/com/even/zaro/config/security/SecurityConfig.java
- src/main/java/com/even/zaro/dto/map/PlaceResponse.java
- src/main/java/com/even/zaro/entity/Favorite.java
- src/main/java/com/even/zaro/entity/FavoriteGroup.java
- src/main/java/com/even/zaro/mapper/FavoriteMapper.java
- src/main/java/com/even/zaro/mapper/GroupMapper.java
- src/main/java/com/even/zaro/mapper/MapMapper.java
- src/main/java/com/even/zaro/repository/FavoriteGroupRepository.java
- src/main/java/com/even/zaro/repository/PlaceRepository.java
- src/main/java/com/even/zaro/service/FavoriteService.java
- src/main/java/com/even/zaro/service/GroupService.java
- src/main/java/com/even/zaro/service/MapService.java
- 멘토링 때 피드백 받은 내용을 수정하고 추가하였습니다.
---
- MapStruct 라이브러리 추가
- @AllArgs -> @RequiredArgs 수정
- @Setter -> 메서드 분리
- 어색한 snake_case -> camelCase 변경
- 인증 없이 그룹, 즐겨찾기 조회할 수 있도록 SecurityConfig 수정
---
---
---
---
- MapStruct 적용해보면서 느낀 점이 이거 굳이 이렇게까지 해야하나.. ?했는데 
(너무 복잡하다고 느낌 ㅠ)
매핑 필드가 5~6개 이상이고, 여러 개발자가 참여하고 있다면 사용하는 것이 좋다고 하네요
```
1. 매핑 로직의 자동화 → 생산성 향상
•	일일이 .builder().fieldA(a.getA())... 하는 코드를 작성하지 않아도 됨
•	컴파일 타임에 매핑 코드 생성 (런타임 Reflection 기반 X → 빠름)
2. 안전성 확보 (컴파일 타임 검증)
•	DTO나 Entity 필드명이 바뀌면 컴파일 에러 발생 → 숨겨진 버그 방지
•	Lombok 없이도 타입 안전하게 매핑 가능
3. 테스트 가능한 정형화된 매핑
•	매핑 로직이 한곳에 집중되어 있어 테스트 및 유지보수가 용이함
•	서비스 코드가 훨씬 깔끔해지고 비즈니스 로직에 집중 가능
```
이런 장점이 있다고 하네요~~.. 
---
- close #118
> Ref/feedback 그룹, 즐겨찾기, 지도 API 멘토링 피드백 반영

- src/main/java/com/even/zaro/dto/comment/CommentResponseDto.java
- src/main/java/com/even/zaro/dto/post/PostDetailResponse.java
- src/main/java/com/even/zaro/dto/post/PostPreviewDto.java
- src/main/java/com/even/zaro/dto/post/PostSearchDto.java
- src/main/java/com/even/zaro/dto/user/UpdateNicknameResponseDto.java
- src/main/java/com/even/zaro/dto/user/UserInfoResponseDto.java
- src/main/java/com/even/zaro/elasticsearch/document/PostEsDocument.java
- src/main/java/com/even/zaro/mapper/PostMapper.java
- src/main/java/com/even/zaro/service/CommentService.java
- src/main/java/com/even/zaro/service/PostEsSearchService.java
- src/main/java/com/even/zaro/service/UserService.java
- src/main/resources/application.yaml
- LocalDateTime 타입 수정
---
- jackson time-zone 설정 제거
- LocalDateTime -> OffsetDateTime 응답 dto에서 타입 변경
- 게시글 작성, 수정, 댓글 작성, 수정, 내 정보 조회, 검색(es)
- PostMapper 헬퍼 매서드 추가 -> @LJIEUN 확인 바랍니다.
---
|게시글 작성| 댓글 작성 | 내 정보 조회
|-----------|----------|----------|
|![image](https://github.com/user-attachments/assets/1c204f43-9f30-4cd0-8f48-03635fa69a05)|![image](https://github.com/user-attachments/assets/e937527c-8ec9-442a-859f-b8c639dce41c)|![image](https://github.com/user-attachments/assets/713f18c6-a408-41f0-8cb4-9d5d7b873144)|
|검색| ES 저장(Z가 붙은 형식의 string)|
|----|-------|
|![image](https://github.com/user-attachments/assets/8833af47-ff8b-4485-a4d1-fc7f2e0321f0)|![image](https://github.com/user-attachments/assets/d105ee02-c93c-4d08-8a35-ef8b9ea42709)|
---
--- …
> Fix/timezone 타임존 문제로 LocalDateTime 타입 수정

- src/main/java/com/even/zaro/controller/FavoriteController.java
- src/main/java/com/even/zaro/dto/group/GroupResponse.java
- src/main/java/com/even/zaro/entity/Favorite.java
- src/main/java/com/even/zaro/entity/FavoriteGroup.java
- src/main/java/com/even/zaro/mapper/GroupMapper.java
- src/main/java/com/even/zaro/repository/FavoriteGroupRepository.java
- src/main/java/com/even/zaro/repository/FavoriteRepository.java
- src/main/java/com/even/zaro/service/FavoriteService.java
- src/main/java/com/even/zaro/service/GroupService.java
- 그룹에 즐겨찾기를 추가, 삭제할 때 그룹 테이블의 즐겨찾기 개수 필드값이 증감하도록 하였습니다.
- 그룹, 즐겨찾기 리스트를 조회할 때, 삭제된 데이터는 조회되지 않도록 수정했습니다.
- 장소에 대해 즐겨찾기 상태를 조회할 수 있는 API를 구현했습니다.
---
- 그룹 조회 시 삭제된 데이터 필터링
- 그룹의 즐겨찾기 조회 시 삭제된 데이터 필터링
- 그룹에 즐겨찾기 개수 필드 추가 (favorite_count)
- 그룹 조회 응답 Dto에 그룹의 즐겨찾기 개수 응답 추가 (groupFavoriteCount)
- 그룹 객체에 즐겨찾기 추가, 삭제에 따른 메서드 추가
(incrementFavoriteCount, decrementFavoriteCount)
- 유저가 해당 장소를 즐겨찾기 추가했는지 조회하는 API 구현
---
> ![스크린샷 2025-06-06 오전 2 08 07](https://github.com/user-attachments/assets/0cb41992-431e-4b6f-8d79-f9419b5fb45d)
- 그룹id 6에 대해서 즐겨찾기 리스트 확인 (placeId 11, 27이 이미 추가되어있음.)
> ![image](https://github.com/user-attachments/assets/6a3c87b9-6f03-433d-a022-37d87731e0b9)
> ![image](https://github.com/user-attachments/assets/6c3312b6-915e-4956-a1ad-3cea46a2d01e)
- placeId 11, 27 로 테스트. …
> Ref/group-favorite 그룹, 즐겨찾기 리팩토링(필드 추가, 필터링, 즐겨찾기 상태 조회API 구현)

- src/main/java/com/even/zaro/global/scheduler/UserScheduler.java
- src/main/java/com/even/zaro/repository/UserRepository.java
- src/main/java/com/even/zaro/service/AuthService.java
- src/test/java/com/even/zaro/integration/UserSchedulerIntegrationTest.java
- src/test/java/com/even/zaro/service/UserServiceTest.java
- 휴면계정 처리
---
- 휴면계정 처리
- 6개월 미접속시 휴면 처리 스케줄러
- 휴면 경과 1년 이상 탈퇴처리 스케줄러
- 탈퇴 30일 경과 정보 영구 삭제 스케줄러 시간 변경
- 로그인시 자동 휴면 복구 처리
---
로그인 시 휴면 자동 해제만 확인
|휴면 계정  | 로그인 | 휴면 해제(ACTIVE)
|---------|--------|---------|
|![image](https://github.com/user-attachments/assets/663c4c2f-cdad-4d4c-a57f-6daa5878afc4)|![image](https://github.com/user-attachments/assets/39f5ccc8-3681-4544-9c62-2306adfea140)|![image](https://github.com/user-attachments/assets/3c3ef045-ed21-4063-acc1-94876c1e38ad)
---
---
- 6개월 1일 지난 회원 휴면처리
- 휴면 후 1년 1일 지난 회원 탈퇴 처리 
---
- 6개월, 1년 후 스케줄러는 테스트 코드로 로직 확인했습니다. 별도 스케줄러 시간 조절로 테스트 하지는 않았습니다.
- 휴면 1개월 전 메일 처리는 이후에 작업할 예정입니다!
---
- 관련 이슈 번호: #88
> Feat/dormant user 휴면계정 처리

- src/main/java/com/even/zaro/controller/AuthController.java
- 로그아웃 API 수정 
---
- 토큰 헤더 자동 추출으로 변경
- 기존 헤더에서 한번 더 전송 필요 -> 헤더에서 자동 추출로 변경
- 리프레시 토큰 쿠키에서 삭제
- 프론트에서 리프레시 토큰은 쿠키에 저장시 HttpOnly로 저장했기에 서버에서 변경해줘야 반영되는 것을 확인.
- 로그아웃 컨트롤러에서 리프레시 토큰 쿠키에서 삭제하는 로직 추가 
---
|기존 - 헤더에서 한번 더 전송 필요| 변경 후 - 헤더에서 자동 추출|
|-----------|-----------|
|![image](https://github.com/user-attachments/assets/38395368-5c95-4d26-aa00-81f0facce1d0)|![image](https://github.com/user-attachments/assets/0a3a1b7d-e255-419c-a2f0-270006ca5e07)|
---
---
---
- 리프레시 토큰은 쿠키에서 잘 삭제되는지 프론트 작업하면서 확인해야할 것 같습니다!
---
> Fix/signout token 로그아웃 API 수정

- src/test/java/com/even/zaro/unit/service/NotificationSseServiceTest.java
- src/test/java/com/even/zaro/unit/util/NotificationMapperTest.java
- NotificationMapper, NotificationSseService 단위테스트 구현
---
- NotificationMapper 단위테스트 구현
- service에서 호출해서 쓰는 비즈니스로직이 많아서, unit.util에 단위테스트 구현했습니당
- NotificationSseService 단위테스트 구현
- connect 메서드, send 메서드 성공/예외 분기
- send는 이미 연결되어 있는 emitter가 존재한다고 가정 후 구현
---
> NotificationMapperTest
> NotificationSseServiceTest
---
---
---
- UserException등은 알림매퍼테스트에서 테스트 하지 않았습니다 (책임 분리, 멘토링 반영)
- sse 참 어렵다 :) .. ~
---
> Test/notification sse : NotificationMapper, NotificationSseService 단위테스트 구현

- src/main/java/com/even/zaro/controller/AuthController.java
- src/main/java/com/even/zaro/global/jwt/JwtAuthFilter.java
- src/main/java/com/even/zaro/service/NotificationSseService.java
- sse 인증을 header사용으로 ref -> 불필요 설정 롤백, 연결유지용 ping 전송 코드 추가
---
- sse 인증을 쿠키->header사용으로 ref 하게되어 생긴 사항들
- 트러블슈팅 ing 참고 : #157  
- 불필요 설정 롤백
- #152 의 쿠키설정을 이전 코드로 롤백
- 쿠키 안 쓰므로, JwtAuthFilter의 쿠키토큰추출 코드 주석처리 (어차피 If문 들어갈 일이 없어지긴 해서 유지해도 되긴합니다)
-  연결유지용 ping 전송 코드 추가
- FE에서 SSE+EventSourcePolyfill 라이브러리로 헤더 사용
- 이 경우 heartbeatTimeout으로 45초 이내에 새로운 이벤트 전송이 없으면, 연결을 끊고 자동 재연결이 됨 (현재경우 넉넉히 65초로 세팅해둠)
- 자동 재연결 시, 자동 헤더 인증은 불가능한 문제 발발
- 따라서 BE에서 30초마다 연결유지용 Ping을 전송해, 연결을 유지하도록 설정함
---
> 서버 실행 시 @PostConstruct로 Ping 작업 초기화
> ![image](https://github.com/user-attachments/assets/ac86cc98-e7dd-4d86-8407-7ffc3c2acb80)
> 30초마다 자동전송되는 ping으로, 알림event 전송이 없어도 sse연결이 끊기지 않음
> ![image](https://github.com/user-attachments/assets/d592bcdf-2153-4e72-915f-34c8e142296b)
> …
> Fix/sse notification : sse 인증을 header사용으로 ref -> 불필요 설정 롤백, 연결유지용 ping 전송 코드 추가

- src/main/java/com/even/zaro/controller/MapController.java
- src/main/java/com/even/zaro/service/MapService.java
- 인근 장소 조회 API 예외 처리 방법 수정 ( 예외를 던지는 것이 아닌 정상 응답에 데이터 null)
---
- 조회된 데이터 없을 시 서비스단에서 null 반환
- 컨트롤러에서 null 일시, "인근에 조회된 장소가 없습니다" 메시지 응답
---
>  <img width="696" alt="image" src="https://github.com/user-attachments/assets/07760e4f-9fb7-49de-b8e2-0d0c27cbc47f" />
- 인근 장소 없을 시 조회된 장소 없습니다 문구 응답
---
---
---
- 프론트단에서 인근 조회 API를 호출할 때마다 console에 오류가 누적되어 정돈하기 위해 작업했습니다.
- 백엔드단에서 예외를 던져버리면 프론트의 client 코드를 수정하는 것이 아닌 이상 
console 에러가 찍히는 것을 피할수가 없었기 때문에 취한 조치입니다,,
---
> ref : 인근 장소 조회 API 예외 처리 방법 수정

- src/main/java/com/even/zaro/controller/NotificationController.java
-  Vercel, EC2 앞단 Nginx에서 버퍼링 비활성화
---
- sse 관련 헤더 직접적인 세팅
- 프록시 버퍼링 비활성화
---
> 로컬환경 잘 작동
---
---
---
- 제발
---
- [SSE 사용중, 로컬에서는 되는데 서버 환경에서는 핑이 안 온다면?](https://velog.io/@hyu-jo/SSE-%EC%82%AC%EC%9A%A9%EC%A4%91-%EB%A1%9C%EC%BB%AC%EC%97%90%EC%84%9C%EB%8A%94-%EB%90%98%EB%8A%94%EB%8D%B0-%EC%84%9C%EB%B2%84-%ED%99%98%EA%B2%BD%EC%97%90%EC%84%9C%EB%8A%94-%ED%95%91%EC%9D%B4-%EC%95%88-%EC%98%A8%EB%8B%A4%EB%A9%B4)
> fix/ping : Vercel, EC2 앞단 Nginx에서 버퍼링 비활성화

- src/main/java/com/even/zaro/controller/CommentController.java
- src/main/java/com/even/zaro/entity/User.java
- src/main/java/com/even/zaro/global/ErrorCode.java
- src/main/java/com/even/zaro/global/scheduler/UserScheduler.java
- src/main/java/com/even/zaro/mapper/CommentMapper.java
- src/main/java/com/even/zaro/mapper/PostMapper.java
- src/main/java/com/even/zaro/repository/UserRepository.java
- src/main/java/com/even/zaro/service/CommentReportService.java
- src/main/java/com/even/zaro/service/PostLikeService.java
- src/main/java/com/even/zaro/service/PostReportService.java
- src/main/java/com/even/zaro/service/PostService.java
- src/main/java/com/even/zaro/service/ProfileService.java
- src/main/java/com/even/zaro/service/UserService.java
- src/test/java/com/even/zaro/integration/user/UserSchedulerIntegrationTest.java
- src/test/java/com/even/zaro/unit/service/UserServiceTest.java
- 회원 정책 수정 및 리팩토링
---
- 회원 리팩토링
- pending 회원 검증 active 회원 검증 로직(deleted, dormant 추가)으로 수정
- 프로필 조회시 active 회원만 조회 가능하도록 메서드 추가 및 적용
- 회원 정책 수정
- 회원 탈퇴 후 정보 30일 후 삭제 -> 3년 후 삭제
- 탈퇴 30일 후 개인정보 임의값으로 변경 스케줄러 추가
- 게시글 리스트, 상세, 댓글 리스트 조회시 탈퇴 회원 "알 수 없는 사용자", 프로필 이미지 null, liveAloneDate null 처리
---
탈퇴 회원 "알 수 없는 사용자" 처리
|게시글 리스트 | 게시글 상세| 댓글 리스트|
|------|------|------|
|![image](https://github.com/user-attachments/assets/37cbece8-59f4-45b3-8e31-d16b8c374d7e)|![image](https://github.com/user-attachments/assets/8b822b60-ac72-4168-bb52-7834c216ea55)|![image](https://github.com/user-attachments/assets/44cf4e28-91a0-4bf1-8a2a-665f512e35d1)|
---
---
---
- post, profile 수정이 있습니다. 확인 바랍니다.
---
- 관련 이슈 번호: FIXES #168
> Fix/user 회원 정책 수정 및 리팩토링

- src/main/java/com/even/zaro/service/NotificationSseService.java
- src/main/java/com/even/zaro/service/ProfileService.java
- 팔로우 기능에서 탈퇴한 사용자는 조회하지 않도록 설정
- [sse] emitter 제거하는 시간을 heartbeatTimeout시간과 맞춤
---
- 팔로우/팔로잉 리스트에서 탈퇴한 사용자는 조회하지 않도록 설정
- 현재의 팔로워/팔로잉 리스트 조회는 탈퇴한 사용자까지 조회가 되더군요,
- 인스타도 탈퇴계정은 팔로우/팔로잉 리스트에 띄우지 않으니 Status.DELETED인 사용자는 조회하지 않도록 설정했습니다
- [sse] emitter 제거하는 시간을 heartbeatTimeout시간과 맞춤
- 클라이언트 heartbeatTimeout 시간을 3시간으로 설정하게되어, 서버 emitter 제거하는 시간도 동일하게 설정했습니다
---
> 기존 user2의 팔로워 리스트
> user3을 softDeleted 처리
> 이후 user2의 팔로워 리스트
---
---
---
- @nahyukk 현재 팔로워/팔로잉 count의 경우 유지됩니다. UserService.softDelete 에서 이 count 계산 또한 처리하는 것이 좋을지도 고민되는군용 ..
- softDeleted된 계정을 restore했을때 팔로우관계는 원래대로 살아있게 되니, Follow 테이블 자체에서 관계를 삭제할 필요는 없을 듯 합니다
- softDeleted된 계정을 restore하는 로직을 찾아도 안 보여서... count 계산을 하게된다면 이 부분에서도 계산이 들어가야할 듯 싶슴다
- count가 현재시점 우선순위는 아니지만 의견 여쭈어보아요
---
> Ref : 팔로우 기능에서 탈퇴한 사용자는 조회하지 않도록 설정 , [sse] emitter 제거하는 시간을 heartbeatTimeout시간과 맞춤

- src/main/java/com/even/zaro/controller/UserController.java
- src/main/java/com/even/zaro/dto/user/UpdateProfileRequestDto.java
- src/main/java/com/even/zaro/entity/User.java
- src/main/java/com/even/zaro/global/ErrorCode.java
- src/main/java/com/even/zaro/global/converter/GenderConverter.java
- src/main/java/com/even/zaro/global/converter/MbtiConverter.java
- src/main/java/com/even/zaro/global/converter/ProviderConverter.java
- src/main/java/com/even/zaro/global/converter/StatusConverter.java
- src/main/java/com/even/zaro/global/validator/EnumValidator.java
- src/main/java/com/even/zaro/global/validator/annotation/ValidEnum.java
- src/main/java/com/even/zaro/service/UserService.java
- src/test/java/com/even/zaro/global/converter/EnumConversionPerformanceTest.java
- src/test/java/com/even/zaro/integration/profile/ProfileIntegrationTest.java
- enum <-> string converter 적용
---
- enum <-> string converter 적용 - user 만 적용
- provider, status
- gender, mbti 
- enum validator 추가
- gender, mbti 에만 적용(request로 받을 때 valid) / provider, status는 내부 로직에만 사용하기에 적용 x
---
enum <-> varchar(10)
enum valid
---
---
---
- 성능 때문이라고 들어서 하기는 했는데.. 차이는 없어보입니다. 대신 가독성과 유지보수 때문에 사용한다고 하네요!
- enum 이름 변경 등.. 
- db는 varchar(10)으로 변경하려는데 그대로 enum으로 둬도 오류가 나지는 않습니다. 그래도 구조적으로 잘못된 것으로 varchar(10)으로 수정해놓겠습니다!
- user만 한번 시도해본 거라.. 제가 구현하지 않은 다른 코드들은 혹시나 틀어질까 건들지 않았습니다.
---
[공부할 때 참고하면 좋을 블로그](https://velog.io/@pood/Spring-DB-%EC%BD%94%EB%93%9C%EA%B0%92%EA%B3%BC-Enum%EC%9D%98-%EB%A7%A4%ED%95%91-%EB%B0%A9%EB%B2%95-Enumerated-vs-Convert)
> Ref/enum converter enum <-> string converter 적용
